### ISSUE TITLE
No wysiwyg editor in admin entries

### ISSUE THREAD

**Issue by ZuluPro** [django-blog-zinnia/zinnia-wysiwyg-wymeditor#1]
Hello,
I tried to use this app with Django 1.7 and 1.8,
I havn't any wysiwyg editor in my admin page.

I tried to manually launch:

``` javascript
$("#id_content").wymeditor({
      skin: "django", lang: "en",
      stylesheet: "/static/zinnia_wymeditor/css/wymeditor_styles.css",
      updateSelector: "input:submit", updateEvent: "click",
      postInit: function(wym) {
          wym.hovertools();
      }
      })
```

Nothing appends...

All seems to be in place: JS/CSS/INSTALLED_APPS, etc...

Do you have any idea of why ?

**Comment by Fantomas42** [comment]
Do you have customized the Entry model ?
Does the wymeditor/jquery.wymeditor.pack.js script is present in the page ?

**Comment by ZuluPro** [comment]
No customization on Entry model,
And the script is present in page's source code in headers:

```
<script type="text/javascript" src="/static/zinnia_wymeditor/js/wymeditor/jquery.wymeditor.pack.js"></script>
```

**Comment by Fantomas42** [comment]
Do you have any interessting informations displayed in the JS console.
Cause it seems related to a JS error.

**Comment by ZuluPro** [comment]
I tried with Firefox and Safari, it works.

But sorry, nothing in Chrome JS console.
I though it was maybe my Chrome version but I tried with a fresh Chromium install and it didn't work.

I'm working on Mac OS X

**Comment by Fantomas42** [comment]
Effectively I have just tested on Chrome/Ubuntu and nothing happen...
I have tested an update the code of WYMEditor, but it's not really easy...

The upgrade seems the better solution, but it will need time.

**Comment by jimr** [comment]
I think this is due to a problem with WYMEditor and JQuery 1.8 (see, e.g. http://stackoverflow.com/questions/13051868/wysiwyg-wymeditor-cant-get-to-load). I've fixed this issue for us by swapping out the bundled jquery.min.js for 1.7.1 that we use elsewhere.

**Comment by Fantomas42** [comment]
Hello,

I don't know why, but I have just tested with Django 1.8.4 and the latest version of each components, and the issue seems to have vanished.

I close the issue.

Regards

**Comment by ZuluPro** [comment]
Hello @Fantomas42
I tested again with a fresh install: Django-1.9.5/django-blog-zinnia-0.16
Same trouble, I don't have WYMEditor with Chrome/MacOS but have with Firefox/MacOS.

Nothing in browser logs...
